export const _TENANT_DATA = [
                {
                    id: "sample-1",
                    property: "Sunrise Luxury Heights #302",
                    location: "Indiranagar, Bangalore",
                    amount: 22000,
                    date: "01 Mar 2026",
                    status: "Paid On-Time",
                    onTime: true,
                },
                {
                    id: "sample-2",
                    property: "Greenwood Villa #12",
                    location: "Koramangala, Bangalore",
                    amount: 18500,
                    date: "02 Feb 2026",
                    status: "Paid On-Time",
                    onTime: true,
                },
                {
                    id: "sample-3",
                    property: "Prestige Lakeview Apt #4B",
                    location: "Whitefield, Bangalore",
                    amount: 25000,
                    date: "01 Jan 2026",
                    status: "Paid On-Time",
                    onTime: true,
                },
                {
                    id: "sample-4",
                    property: "Sunrise Luxury Heights #302",
                    location: "Indiranagar, Bangalore",
                    amount: 22000,
                    date: "03 Dec 2025",
                    status: "Paid On-Time",
                    onTime: true,
                },
                 {
                    id: "sample-3",
                    property: "Prestige Lakeview Apt #4B",
                    location: "Whitefield, Bangalore",
                    amount: 25000,
                    date: "01 Jan 2026",
                    status: "Paid On-Time",
                    onTime: true,
                },
                {
                    id: "sample-4",
                    property: "Sunrise Luxury Heights #302",
                    location: "Indiranagar, Bangalore",
                    amount: 22000,
                    date: "03 Dec 2025",
                    status: "Paid On-Time",
                    onTime: true,
                },
            ];